# Generated by Django 4.0.1 on 2022-01-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_renew_loan', 'Pode renovar emprestimo'),)},
        ),
    ]
