# Generated by Django 4.0.1 on 2022-01-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_handle_author', 'Manipula cadastro de autores.'),)},
        ),
    ]
